### ISSUE TITLE
asset mov 등록하는 restAPI 생성.

### ISSUE THREAD

**Issue by khw7096** [digital-idea/csi3#4]

**Comment by khw7096** [comment]
https://github.com/digital-idea/csi3/commit/199457d1c0c08428fb59406ce26c0796b041a389

**Comment by khw7096** [comment]
실제로 잘 작동되는지 테스트 진행.

**Comment by seonill** [comment]
name 이라....괜찮네용! 사실 이 부분에 대해 오늘 많은 고민을 햇었는데.. 출근하시면 같이 또 이야기해보아요~~

**Comment by khw7096** [comment]
좋아용~

**Comment by khw7096** [comment]
테스트 완료.
